language: java
install: true
jdk:
  - oraclejdk8

branches:
  only:
  - master

script:
  - mvn -Denv=dev clean test

after_success:
  - mvn jacoco:report coveralls:report

notifications:
  email:
    recipients:
      - its-iam-web-app-devs@lists.hawaii.edu
      - duckart@hawaii.edu
      - zknoebel@hawaii.edu
      - aaronvil@hawaii.edu
    on_success: change
    on_failure: always
